# Generated by Django 4.2.2 on 2023-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0002_tag_rename_article_text_article_text_article_author_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="age",
            field=models.IntegerField(),
        ),
    ]
